defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      render_with_liquid: false

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
